export default [
    {
        name: "account_expense_category_id",
        label: "Slect category",
        type: "select",
        disabled: true,
        value: "",
        data_list: [],
    },
    {
        name: "date",
        label: "date",
        type: "date",
        disabled: true,
        value: moment().format("YYYY-MM-DD"),
    },
    {
        name: "name",
        label: "whose voucher",
        type: "text",
        disabled: true,
        value: "",
    },
    {
        name: "folio",
        label: "folio",
        type: "number",
        disabled: true,
        value: "",
    },
    {
        name: "creator_name",
        label: "created by",
        type: "text",
        disabled: true,
        value: "",
    },
    {
        name: "description",
        label: "description",
        type: "text",
        disabled: true,
        value: "",
    },
    {
        name: "reason",
        label: "reason",
        type: "text",
        disabled: true,
        value: "",
    },
    {
        name: "amount",
        label: "amount",
        type: "number",
        disabled: true,
        value: "",
    },
    {
        name: "amount_in_text",
        label: "amount in text",
        type: "text",
        disabled: true,
        value: "",
    },
    {
        name: "image",
        label: "Upload image",
        type: "file",
        disabled: true,
        value: "",
        multiple: false,
    },
];
